/*****************************************************************************
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*****************************************************************************/

#include <iostream>

int main()
{
	long max_value = 4000000;
	long long sum = 0;

	long fn_2 = 1;
	long fn_1 = 2;
	long fn = fn_1 + fn_2;

	sum += 2;
	while (fn <= max_value)
	{
		if (fn % 2 == 0)
		{
			sum += fn;
		}
		
		fn_2 = fn_1;
		fn_1 = fn;
		fn = fn_1 + fn_2;
	}

    std::cout << "result is " << sum << std::endl;
}

